version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.backend
    container_name: gateway-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ../config:/app/config
    networks:
      - gateway-network

  frontend:
    build:
      context: ..
      dockerfile: deploy/Dockerfile.frontend
    container_name: gateway-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8080
    networks:
      - gateway-network
    depends_on:
      - backend

networks:
  gateway-network:
    driver: bridge
