mqtt:
  broker: "tcp://broker.hivemq.com:1883"
  topics:
    test/topic1: 0  # 主题1, QoS = 0
    test/topic2: 1  # 主题2, QoS = 1
    test/topic3: 2  # 主题3, QoS = 2
#    QoS 级别
#    0：最多一次交付（At most once）。消息可能丢失，不会有重试。
#    1：至少一次交付（At least once）。消息会至少发送一次，可能会有重复消息。
#    2：仅一次交付（Exactly once）。消息保证只会到达一次，最安全的 QoS。
  clientID: "gateway"
  username:
  password:
  maxReconnectInterval: 10s