log:
  log_path: ./logs
  # MaxSize：在进行切割之前，日志文件的最大大小（以MB为单位）
  max_size: 600
  # MaxBackups：保留旧文件的最大个数
  max_backups: 1000
  # MaxAge：保留旧文件的最大天数
  max_age: 30
  # Compress：是否压缩/归档旧文件
  compress: true
  level: debug

script:
  dir: ./script



connector:
  type: mqtt

strategy:
  - type: influxdb
    enable: true
    url: http://10.17.191.107:8086
    token: mK_0NkLVPW8THIYkn52eqr7enL6IinGp8d5xbXizO1mVxAEk_EuOFxZ9OKWYcwVgi2XmogD6iPcO9KQ8ToVvtQ==
    org: "byd"
    bucket: "test"
    batch_size: 2000
    filter: # 格式<设备类型>:<设备名称>:<遥测名称>
       - ".*:.*:.*"
#       - "vobc\\.info:vobc.*:RIOM_sta_3"
    tags:
      - "data_source"
  - type: iotdb
    enable: false
    url: "127.0.0.1:6667,127.0.0.1:6668,127.0.0.1:6669"
    username:
    password:
    batch_size:

#  - type: mqtt
#    enable: false
#    url: tcp://
#    topic: "sam"
#    filter: # 格式<设备类型>:<设备名称>:<遥测名称>
#      - ".*:.*:.*"
