proto-train2sam-v0.0.1:
  chunks:
    - type: FixedLengthChunk
      length: 1245
      sections:
        - from: # 没有解码方式的即为不用处理，jump即可
            byte: 92
        - from:
            byte: 2
          decoding:
            method: "BytesToBigEndianInt"
          to:
            device: "${device_id}"
            type: "info"
            fields:
              - ver
        - from:
            byte: 10
        - from:
            byte: 1
          decoding:
            method: "DecodeByteToLittleEndianBits"
          to:
            device: "${device_id}"
            type: "info"
            fields:
              - RIOM_sta_{1..8}
          desc: "帧长度 长度由字节69开始计算" #字段说明
        - from:
            byte: 14
        - from:
            byte: 1
          decoding:
            method: "DecodeByteToLittleEndianBits"
          to:
            device: "${device_id}"
            type: "traction_system"
            fields:
              - field_{1..4}









